//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataLabelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataLabel {
            get {
                return this.DataLabelField;
            }
            set {
                if ((object.ReferenceEquals(this.DataLabelField, value) != true)) {
                    this.DataLabelField = value;
                    this.RaisePropertyChanged("DataLabel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auther", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class Auther : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArticalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Artical {
            get {
                return this.ArticalField;
            }
            set {
                if ((object.ReferenceEquals(this.ArticalField, value) != true)) {
                    this.ArticalField = value;
                    this.RaisePropertyChanged("Artical");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionHandelingInWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class ExceptionHandelingInWCF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotelSearchRequest", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class HotelSearchRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string destinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApplication1.ServiceReference1.Party guestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nightsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                if ((object.ReferenceEquals(this.destinationField, value) != true)) {
                    this.destinationField = value;
                    this.RaisePropertyChanged("destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApplication1.ServiceReference1.Party guests {
            get {
                return this.guestsField;
            }
            set {
                if ((object.ReferenceEquals(this.guestsField, value) != true)) {
                    this.guestsField = value;
                    this.RaisePropertyChanged("guests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nights {
            get {
                return this.nightsField;
            }
            set {
                if ((this.nightsField.Equals(value) != true)) {
                    this.nightsField = value;
                    this.RaisePropertyChanged("nights");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Party", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class Party : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApplication1.ServiceReference1.Guest[] adultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfApplication1.ServiceReference1.Guest[] kidsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApplication1.ServiceReference1.Guest[] adults {
            get {
                return this.adultsField;
            }
            set {
                if ((object.ReferenceEquals(this.adultsField, value) != true)) {
                    this.adultsField = value;
                    this.RaisePropertyChanged("adults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfApplication1.ServiceReference1.Guest[] kids {
            get {
                return this.kidsField;
            }
            set {
                if ((object.ReferenceEquals(this.kidsField, value) != true)) {
                    this.kidsField = value;
                    this.RaisePropertyChanged("kids");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Guest", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class Guest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char GuestTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char GuestType {
            get {
                return this.GuestTypeField;
            }
            set {
                if ((this.GuestTypeField.Equals(value) != true)) {
                    this.GuestTypeField = value;
                    this.RaisePropertyChanged("GuestType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="hotelsummary", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class hotelsummary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countrycodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hotelidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationdescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lowrateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string postalcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ratecurrencycodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shortdescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string thumbnailurlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tripadvisorratingurlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.address1Field, value) != true)) {
                    this.address1Field = value;
                    this.RaisePropertyChanged("address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string countrycode {
            get {
                return this.countrycodeField;
            }
            set {
                if ((object.ReferenceEquals(this.countrycodeField, value) != true)) {
                    this.countrycodeField = value;
                    this.RaisePropertyChanged("countrycode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hotelid {
            get {
                return this.hotelidField;
            }
            set {
                if ((object.ReferenceEquals(this.hotelidField, value) != true)) {
                    this.hotelidField = value;
                    this.RaisePropertyChanged("hotelid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string locationdescription {
            get {
                return this.locationdescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.locationdescriptionField, value) != true)) {
                    this.locationdescriptionField = value;
                    this.RaisePropertyChanged("locationdescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lowrate {
            get {
                return this.lowrateField;
            }
            set {
                if ((object.ReferenceEquals(this.lowrateField, value) != true)) {
                    this.lowrateField = value;
                    this.RaisePropertyChanged("lowrate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string postalcode {
            get {
                return this.postalcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.postalcodeField, value) != true)) {
                    this.postalcodeField = value;
                    this.RaisePropertyChanged("postalcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ratecurrencycode {
            get {
                return this.ratecurrencycodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ratecurrencycodeField, value) != true)) {
                    this.ratecurrencycodeField = value;
                    this.RaisePropertyChanged("ratecurrencycode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shortdescription {
            get {
                return this.shortdescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.shortdescriptionField, value) != true)) {
                    this.shortdescriptionField = value;
                    this.RaisePropertyChanged("shortdescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string thumbnailurl {
            get {
                return this.thumbnailurlField;
            }
            set {
                if ((object.ReferenceEquals(this.thumbnailurlField, value) != true)) {
                    this.thumbnailurlField = value;
                    this.RaisePropertyChanged("thumbnailurl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tripadvisorratingurl {
            get {
                return this.tripadvisorratingurlField;
            }
            set {
                if ((object.ReferenceEquals(this.tripadvisorratingurlField, value) != true)) {
                    this.tripadvisorratingurlField = value;
                    this.RaisePropertyChanged("tripadvisorratingurl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddData", ReplyAction="http://tempuri.org/IService1/AddDataResponse")]
        void AddData(WpfApplication1.ServiceReference1.Data s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddData", ReplyAction="http://tempuri.org/IService1/AddDataResponse")]
        System.Threading.Tasks.Task AddDataAsync(WpfApplication1.ServiceReference1.Data s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrentData", ReplyAction="http://tempuri.org/IService1/GetCurrentDataResponse")]
        WpfApplication1.ServiceReference1.Data[] GetCurrentData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrentData", ReplyAction="http://tempuri.org/IService1/GetCurrentDataResponse")]
        System.Threading.Tasks.Task<WpfApplication1.ServiceReference1.Data[]> GetCurrentDataAsync();
        
        // CODEGEN: Generating message contract since the wrapper name (AutherRequest) of message AutherRequest does not match the default value (GetInfo)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInfo", ReplyAction="http://tempuri.org/IService1/GetInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceReference1.ExceptionHandelingInWCF), Action="http://tempuri.org/IService1/GetInfoExceptionHandelingInWCFFault", Name="ExceptionHandelingInWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
        WpfApplication1.ServiceReference1.AuthorResponse GetInfo(WpfApplication1.ServiceReference1.AutherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInfo", ReplyAction="http://tempuri.org/IService1/GetInfoResponse")]
        System.Threading.Tasks.Task<WpfApplication1.ServiceReference1.AuthorResponse> GetInfoAsync(WpfApplication1.ServiceReference1.AutherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHotels", ReplyAction="http://tempuri.org/IService1/GetHotelsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceReference1.ExceptionHandelingInWCF), Action="http://tempuri.org/IService1/GetHotelsExceptionHandelingInWCFFault", Name="ExceptionHandelingInWCF", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
        WpfApplication1.ServiceReference1.hotelsummary[] GetHotels(WpfApplication1.ServiceReference1.HotelSearchRequest Req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHotels", ReplyAction="http://tempuri.org/IService1/GetHotelsResponse")]
        System.Threading.Tasks.Task<WpfApplication1.ServiceReference1.hotelsummary[]> GetHotelsAsync(WpfApplication1.ServiceReference1.HotelSearchRequest Req);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutherRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutherRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Username;
        
        public AutherRequest() {
        }
        
        public AutherRequest(string Username) {
            this.Username = Username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WpfApplication1.ServiceReference1.Auther auhther;
        
        public AuthorResponse() {
        }
        
        public AuthorResponse(WpfApplication1.ServiceReference1.Auther auhther) {
            this.auhther = auhther;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WpfApplication1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WpfApplication1.ServiceReference1.IService1>, WpfApplication1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddData(WpfApplication1.ServiceReference1.Data s) {
            base.Channel.AddData(s);
        }
        
        public System.Threading.Tasks.Task AddDataAsync(WpfApplication1.ServiceReference1.Data s) {
            return base.Channel.AddDataAsync(s);
        }
        
        public WpfApplication1.ServiceReference1.Data[] GetCurrentData() {
            return base.Channel.GetCurrentData();
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.ServiceReference1.Data[]> GetCurrentDataAsync() {
            return base.Channel.GetCurrentDataAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplication1.ServiceReference1.AuthorResponse WpfApplication1.ServiceReference1.IService1.GetInfo(WpfApplication1.ServiceReference1.AutherRequest request) {
            return base.Channel.GetInfo(request);
        }
        
        public WpfApplication1.ServiceReference1.Auther GetInfo(string Username) {
            WpfApplication1.ServiceReference1.AutherRequest inValue = new WpfApplication1.ServiceReference1.AutherRequest();
            inValue.Username = Username;
            WpfApplication1.ServiceReference1.AuthorResponse retVal = ((WpfApplication1.ServiceReference1.IService1)(this)).GetInfo(inValue);
            return retVal.auhther;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplication1.ServiceReference1.AuthorResponse> WpfApplication1.ServiceReference1.IService1.GetInfoAsync(WpfApplication1.ServiceReference1.AutherRequest request) {
            return base.Channel.GetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.ServiceReference1.AuthorResponse> GetInfoAsync(string Username) {
            WpfApplication1.ServiceReference1.AutherRequest inValue = new WpfApplication1.ServiceReference1.AutherRequest();
            inValue.Username = Username;
            return ((WpfApplication1.ServiceReference1.IService1)(this)).GetInfoAsync(inValue);
        }
        
        public WpfApplication1.ServiceReference1.hotelsummary[] GetHotels(WpfApplication1.ServiceReference1.HotelSearchRequest Req) {
            return base.Channel.GetHotels(Req);
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.ServiceReference1.hotelsummary[]> GetHotelsAsync(WpfApplication1.ServiceReference1.HotelSearchRequest Req) {
            return base.Channel.GetHotelsAsync(Req);
        }
    }
}
